### PR TITLE
Cleanup project angkringan amikom

### PR DESCRIPTION
**Pull request by rizalarfiyan**
Cleanup project angkringan amikom

### CODE REVIEW

**Comment by Ahmad-mufied** [comment]
Having thoroughly evaluated your code, I'm impressed by the elegance and efficiency of your implementation. Great job!

**Comment by rizalarfiyan** [comment]
di approve bang, bukan di close @Ahmad-mufied  :rofl::rofl::rofl:

**Comment by Ahmad-mufied** [comment]
salah pencet Zal wkwkw

**Comment by rizalarfiyan** [comment]
> salah pencet Zal wkwkw

siapp wkwk

**Review by Ahmad-mufied — APPROVED** [review]

**Comment by rizalarfiyan** [comment]
thanks masseh @Ahmad-mufied

**Pull request merged**
